/** We have created a table to represent the product id with their total revenue generated by excluding those products 
which are returned or going to be returned.    **/
create view total_product_revenue AS 
with order_detail_new as (
                          Select *
                          From order_detail
                          where order_detail_id Not in (Select order_detail_id 
                                                        From returns
                                                        Where refund_status = "Approved"
                                                        or refund_status = "Processed")
						 )
Select
      n.product_id,
      p.product_name,
      round(sum((n.quantity*n.unit_price)*((100-n.discount_percent)/100)),2) AS total_revenue
From order_detail_new as n
Left join products as p
On n.product_id = p.product_id
group by n.product_id,p.product_name;

/** We have created a table to find out the total amount or selling price of each order detail id by using View. **/
create view amount AS
Select
      *,
      round((quantity*unit_price)*((100-discount_percent)/100),2) AS total_amount
From order_detail;
select * from amount;
select * from total_product_revenue;